### ISSUE TITLE
add ability to set default environment

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#114]
when restarting the container the user has to go in and select the environment. Ideally there would be either a checkbox to set a known default environment or 'use last' when restarting the container

**Comment by nembery** [comment]
can't fix. The environments file is encrypted on disk and we never have access to the user password to store it to un-encrypt it later. I.E. a user supplied password is always required to open and read the file. This is by design and 'fixing' it would require a rewrite of the env stuff that would make it way less secure.
