### ISSUE TITLE
pan_validation skillets not loading in latest version

### ISSUE THREAD

**Issue by glspi** [PaloAltoNetworks/panhandler#191]
When attempting to load any pan_validation skillet, the page to input variable for the template never loads, a panhandler error page loads instead.

## Expected behavior

The skillet page should load allowing you to input variables based on the skillet, before then running the skillet.

## Current behavior

Traceback error in views.py
Error here: http://dpaste.com/1NRTSA5

## Steps to reproduce

1. Find any pan_validation skillet in your collection (I have been testing with IronSkillet validations mainly, but also effects example 'get hostname' skillet/etc)
2. Click 'go'
3. Error page loads

## Screenshots

![image](https://user-images.githubusercontent.com/24619595/80118598-dd48e100-8545-11ea-8b82-f4d892bd6090.png)

## Context

Just trying to run a skillet.

## Your Environment

- Version used:  Version: 3.1 2020-04-20T15:56:07
- Environment name and version: Chrome Version 80.0.3987.163 (Official Build) (64-bit), also happens in Firefox 74.0 (64-bit).
- Operating System and version (desktop or mobile): MacOS 10.13.6, panhandler docker container being run on Ubuntu 18.0.4.
- Link to your project: This happens with Palo provided example pan_validation skillets.

**Comment by nembery** [comment]
Thanks for the bug report. This is  now fixed in master branch and a new image has been built and pushed to docker hub. You can update to the latest with 

```bash

curl -s -k -L http://bit.ly/2xui5gM | bash

```

The issue was that we were not tracking django versions explicitly and the recent move to 3.0 broke some things. Fix was to adjust the various module paths, but also to stick the tested version requirements to an exact release number. 

Really appreciate the report.

**Comment by glspi** [comment]
Thanks! Can confirm it's working again after the update.
