### ISSUE TITLE
Repositories that require login stop import processing until credentials are entered

### ISSUE THREAD

**Issue by punisherVX** [PaloAltoNetworks/panhandler#23]
The internal github Enterprise server requires a user login EVERY time a clone is done.  In panhandler, this means that when importing a skillet repository, the user has to enter their username and password.  This means they either have to attach to the docker container and enter their id and password and hit enter, or if they are running it via source, they need to submit the username/password on the cmd line of their server and then processing continues.

**Comment by nembery** [comment]
can they use SSH based credentials?

**Comment by nembery** [comment]
This was fixed in cnc commit: 55e7f2b9ed430ee9f1644601c983ad7d63f4835b. The fix is to use the GIT_ASKPASS env var when we detect an http like URL scheme. Since this is in a container, private repos using http can't be supported, The user must use SSH based auth in this case (which is better). ASKPASS points to fake binary which will always cause auth to fail fast. This usually only happens when a user enters a git URL that doesn't exist
